export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const GET_DETAIL = "GET_DETAIL";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const ORDER_BY = "ORDER_BY";
export const TEMPERAMENT_FILTER = "TEMPERAMENT_FILTER";
export const SOURCE_FILTER = "SOURCE_FILTER";
